# __init__.py

from .sql_commands import (
    CREATE_SONGS_TABLE,
    CREATE_USERS_TABLE,
    CREATE_LISTENING_HISTORY_TABLE,
    CREATE_DATA_METADATA_TABLE,
    INSERT_SONG,
    INSERT_USER,
    INSERT_LISTENING_HISTORY,
    UPDATE_METADATA,
    CREATE_TABLE_COMMANDS
)

__all__ = [
    'CREATE_SONGS_TABLE',
    'CREATE_USERS_TABLE',
    'CREATE_LISTENING_HISTORY_TABLE',
    'CREATE_DATA_METADATA_TABLE',
    'INSERT_SONG',
    'INSERT_USER',
    'INSERT_LISTENING_HISTORY',
    'UPDATE_METADATA',
    'CREATE_TABLE_COMMANDS'
]